replicaCount: 1

image:
  repository: nivisha/spring-app-helm
  pullPolicy: IfNotPresent
  tag: latest

serviceAccount:
  create: true

service:
  type: ClusterIP
  port: 8081

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: niviapp.com
      paths:
        - path: /api
          pathType: Prefix
  tls: []

resources: {}
livenessProbe:
  httpGet:
    path: /api/msg/welcome
    port: 8081
readinessProbe:
  httpGet:
    path: /api/msg/welcome
    port: 8081

autoscaling:
  enabled: false

nodeSelector: {}
tolerations: []
affinity: []

